import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ThemeProvider } from "next-themes";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Let us Echo",
  description: "Generated by Echo Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* <script
          src="https://ternkonnect-widget.vercel.app/widget.js"
          data-account="Y4TeKv2Ybm"
        ></script> */}

        {/* <script
          src="https://cdn.ternkonnect.com/widget.js"
          data-account="Y4TeKv2Ybm"
        ></script> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <NavBar /> */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>

          {children}
          <ToastContainer />
        </ThemeProvider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
